apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name | quote }}
  labels:
    circleci.com/component-name: {{ .Values.componentName | quote }}
spec:
  ingressClassName: nginx
  rules:
    # host: domain.foo.org add a host if you want to test
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name | quote }}
            port:
              number: 80
