apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cci-rollout-demo
  annotations:
    circleci.com/project-id: b23cfab9-53d0-400c-947c-2748406ddb3d
  labels:
    circleci.com/component-name: cci-rollout-demo
    circleci.com/version: v1.0
spec:
  replicas: 2
  revisionHistoryLimit: 5
  rollbackWindow:
    revisions: 3
  strategy:
    canary:
      steps:
      - setWeight: 15
      - pause: {duration: "5m"}
      - setWeight: 50
      - pause: {duration: "5m"}
      - setWeight: 100
      - pause: {duration: "5m"}
  selector:
    matchLabels:
      circleci.com/component-name: cci-rollout-demo
  template:
    metadata:
      labels:
        circleci.com/component-name: cci-rollout-demo
        circleci.com/version: v1.0
    spec:
      containers:
        - image: argoproj/rollouts-demo:purple
          imagePullPolicy: Always
          name: color-demo
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
          ports:
            - containerPort: 8080
              protocol: TCP
